# -- 코드를 입력하세요
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE  NOT EXISTS (SELECT ANIMAL_ID
                  FROM ANIMAL_OUTS
                  WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID)
ORDER BY DATETIME
LIMIT 3;

# SELECT *
# FROM ANIMAL_INS
# LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID;